version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    directory: "/GoodFriend.Plugin"
    schedule:
      interval: "monthly"

  - package-ecosystem: "nuget"
    directory: "/GoodFriend.Client"
    schedule:
      interval: "monthly"

  - package-ecosystem: "cargo"
    directory: "/GoodFriend.Api"
    schedule:
      interval: "monthly"