version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/GoodFriend.Plugin"
    schedule:
      interval: "monthly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/GoodFriend.Server"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
