project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: true
append_commit_message: true
files:
  - source: /src/Plugin/Localization/Resources/Strings.resx
    translation: /%original_path%/Strings.%two_letters_code%.resx
