name: "API Changes"

on:
  push:
    branches: ["main"]
    paths:
      - "src/Api/**.rs"
      - "src/Api/Cargo.toml"
      - "src/Api/Cargo.lock"
  pull_request:
    branches: ["main"]
    paths:
      - "src/Api/**.rs"
      - "src/Api/Cargo.toml"
      - "src/Api/Cargo.lock"
    types: [ready_for_review, opened, synchronize]
  workflow_dispatch:

jobs:
  Test:
    if: github.event.pull_request.draft == false || github.event_name == 'push'
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: ./src/Api/
    strategy:
        matrix:
          rust: [stable]
    steps:
      - name: GitHub Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Setup Rust Toolchain and Cache
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt, clippy
          cache: true
          toolchain: stable

      - name: Build Project
        run: cargo build --all

      - name: Run Tests
        run: cargo test --all

      - name: Run Clippy
        run: cargo clippy --all -- -D warnings

      - name: Run Rustfmt
        run: cargo fmt --all --check
