name: "Client Changes"

on:
  push:
    branches: ["main"]
    paths:
      - "GoodFriend.Client/**.cs"
      - "GoodFriend.Client/*.csproj"
      - "GoodFriend.Client/packages.lock.json"
  pull_request:
    branches: ["main"]
    paths:
      - "GoodFriend.Client/**.cs"
      - "GoodFriend.Client/*.csproj"
      - "GoodFriend.Client/packages.lock.json"
    types: [ready_for_review, opened, synchronize]

jobs:
  Test:
    if: github.event.pull_request.draft == false || github.event_name == 'push'
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    defaults:
        run:
          working-directory: ./GoodFriend.Client/
    strategy:
        matrix:
          dotnet: [7.0.x]
    env:
        DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - name: GitHub Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive
    
      - name: Cache Nuget Packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
            dotnet-version: ${{ matrix.dotnet }}
            include-prerelease: true
        
      - name: Restore Nuget Packages
        run: dotnet restore

      - name: Build Client
        run: dotnet build --no-restore --no-logo

      - name: Check for Lint Errors
        id: lint
        working-directory: Wholist
        continue-on-error: true
        run: | 
          dotnet format --verify-no-changes > lint.txt 2>&1

      - name: Report Lint Errors
        working-directory: Wholist
        if : steps.lint.outcome == 'failure'
        run: |
          cat lint.txt | sed -E 's/^(.*)$/::warning:: \1/g'

      - name: Run Tests
        run: dotnet test --no-restore --no-build --verbosity normal
