name: "Test Docker"

on:
  pull_request:
    branches: ["main"]
    paths:
      - "src/Server/Dockerfile"
      - "src/Server/.dockerignore"
    types: [ready_for_review, opened, synchronize]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./src/Server/
          file: ./src/Server/Dockerfile
          push: false
          tags: testbuild/testbuild:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
