name: "Test API"

on:
  push:
    branches: ["main"]
    paths:
      - "src/Api/**.rs"
      - "src/Api/Cargo.toml"
      - "src/Api/Cargo.lock"
  pull_request:
    branches: ["main"]
    paths:
      - "src/Api/**.rs"
      - "src/Api/Cargo.toml"
      - "src/Api/Cargo.lock"
    types: [ready_for_review, opened, synchronize]

jobs:
  Test:
    if: github.event.pull_request.draft == false || github.event_name == 'push'
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: ./src/Api/
    strategy:
        matrix:
          rust: [stable]
    steps:
      - name: GitHub Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Setup Rust toolchain
        uses: hecrj/setup-rust-action@v2
        with:
          toolchain: stable
          components: rustfmt, clippy
            
      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: "./src/Api/"

      - name: Run Tests
        run: cargo test --all

      - name: Run Clippy
        run: cargo clippy --all -- -D warnings

      - name: Run Rustfmt
        run: cargo fmt --all --check
